# This file was generated by GoReleaser. DO NOT EDIT.
class Hssh < Formula
  desc ""
  homepage ""
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/squarescale/hssh/releases/download/v0.1.3/hssh_0.1.3_darwin_amd64.tar.gz"
    sha256 "2dee58eb3fcc88f47e344ae753ae500a75e0c45a94925f42f55d9227c0b03e2f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/squarescale/hssh/releases/download/v0.1.3/hssh_0.1.3_linux_amd64.tar.gz"
      sha256 "33f413f0f1b4e293f6432021bf977cf74cebfb35a1b75b9ea65e20afa62895e3"
    end
  end

  def install
    bin.install "hssh"
  end
end
