# This file was generated by GoReleaser. DO NOT EDIT.
class Hssh < Formula
  desc ""
  homepage ""
  version "0.0.9"

  if OS.mac?
    url "https://github.com/squarescale/hssh/releases/download/v0.0.9/hssh_0.0.9_darwin_amd64.tar.gz"
    sha256 "40d474e7ff6ff6b3865f3b47c46b6aed54647350be71cc5402af901f229cfdc9"
  elsif OS.linux?
    url "https://github.com/squarescale/hssh/releases/download/v0.0.9/hssh_0.0.9_linux_amd64.tar.gz"
    sha256 "02c096824d49ce3531e5ddc4dfc4b0acbdaad3c7aeaa021e1aded85d6c2c525c"
  end

  def install
    bin.install "hssh"
  end
end
